language: python
python:
  - "2.7"
env:
  - DJANGO=1.4
  - DJANGO=1.5
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q mock --use-mirrors
  - pip install -q pep8 --use-mirrors
  - pip install -q https://github.com/dcramer/pyflakes/tarball/master
  - pip install -e . --use-mirrors
before_script:
  - "pep8 --ignore=W293 payments"
  - pyflakes payments
script:
  - python runtests.py