language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.4
  - DJANGO=1.5
  - DJANGO=1.6
install:
  - pip install flake8
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q django-jsonfield==0.8.12
  - pip install -q django-forms-bootstrap
  - pip install -q mock --use-mirrors
  - pip install -q django-nose --use-mirrors
  - pip install -q coverage --use-mirrors
  - pip install -q python-coveralls --use-mirrors
  - pip install -e . --use-mirrors
script:
  - flake8 .
  - coverage run runtests.py
after_script:
  - coveralls
